# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d19d04b944621fa0daf617a0f7cbe78f05bba13fb0b93e27ea030860868b401cc84d6605ee06070f76ff01d43b5cb61f3c8f2e100ff0ba6953bee0b0d8db19f

test:
  secret_key_base: 7cc6e8272a71b00895909f6b4cd9ec79ec224ed0055ee6078ffea68792cb6e569d99b21cac3e87ccd5dc809d8080b6aff0074db58dc18e68a03498b651643fb6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

MAILCHIMP_API_KEY: dceaa87f2df98e31aa156c1c1dd533b3-us12
MAILCHIMP_LIST_ID: 841ace3bb6
